const mergedFilteredTaviCases = [
    {
        id: 361,
        doi: "10.1001/jamacardio.2018.1579",
        pmid: "29926107",
        title: "71-Year-Old Man With Recurrent Dyspnea Following Transcatheter Aortic Valve Replacement Diagnosis Bioprosthetic valve thrombosis following TAVR",
        source: "JAMA CARDIOLOGY",
        author: "Timothy F Simpson",
        abstract: "N/A",
        keywords: null,
        year: 2018,
        Basic_Info: {
            Age: "71",
            Gender: "Male",
            Case: "Recurrent dyspnea following transcatheter aortic valve replacement (TAVR)",
            Previous_History: "Symptomatic aortic stenosis, nonobstructive coronary artery disease"
        },
        Pre_Info: {
            Mean_Gradient: "14 mmHg",
            Peak_Gradients: "29 mmHg",
            Valve_Area: "N/A",
            Maximum_Velocity: "N/A",
            Ejection_Fraction: "N/A"
        },
        Procedure: {
            Valve_Diameter: "N/A",
            Valve_Type: "N/A"
        },
        Result: {
            Death: false,
            Paravalvular_Leak: false,
            Mean_Gradient: "N/A",
            Peak_Gradients: "N/A",
            Valve_Area: "N/A",
            Maximum_Velocity: "N/A"
        },
        Files: {
            PDF: "D:/Romy/SAIRI/TAVI/Code/pdf_downloads/10.1001_jamacardio.2018.1579.pdf",
            Images: [
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1001_jamacardio.2018.1579/images/a9e8d13f631de645e240ba74ab843ed68e86603a994e0f4a53eb2ed0a78e43d5.jpg",
                    caption: "Short-axis 4-dimensional computed tomography angiography of the balloon expandable transcatheter aortic valve 12 months after implantation in diastole demonstrating thickened, nodular bioprosthetic leaflets within a. cobalt-chromium frame (A) and in early systole demonstrating thickened, nodular hypoattenuating opacities involving the. base of the leaflets (B)."
                }
            ]
        },
        Baseline_Characteristics: {
            Age: 71,
            Sex: "Male",
            Body_Mass_Index_BMI: "N/A",
            Surface_Area: "N/A",
            Diabetes_Mellitus: "N/A",
            Hypertension: "N/A",
            Hyperlipidemia: "N/A",
            Coronary_Artery_Disease: true,
            Chronic_Obstructive_Pulmonary_Disease_COPD: "N/A",
            Dialysis: "N/A",
            Atrial_Fibrillation: "N/A",
            New_York_Heart_Association_NYHA_Classification: "N/A",
            Angiotensin_Converting_Enzyme_Inhibitor_ACEI_or_Angiotensin_II_Receptor_Blocker_ARB: "N/A",
            Beta_Receptor_Blocker: true,
            Calcium_Ion_Blocker: "N/A",
            Diuretic: "N/A",
            Aspirin: true,
            Anticoagulant: "N/A",
            Statins: true,
            Myocardial_Infarction: "N/A",
            Percutaneous_Coronary_Intervention_PCI: "N/A",
            Coronary_Artery_Bypass_Grafting_CABG: "N/A",
            Society_of_Thoracic_Surgeons_STS_Score: "N/A",
            N_Terminal_Pro_B_Type_Natriuretic_Peptide_NT_proBNP: 55
        },
        Preprocedural_Imaging_Assessment: {
            Left_Ventricular_Ejection_Fraction_LVEF: "N/A",
            Aortic_Valve_Maximum_Transvalvular_Pressure_Gradient_Max_PG: "N/A",
            Aortic_Valve_Mean_Transvalvular_Pressure_Gradient_Mean_PG: 29,
            Aortic_Valve_Effective_Orifice_Area_EOA: "N/A",
            Aortic_Valve_Effective_Orifice_Area_Index_EOAI: "N/A",
            Greater_Equal_Moderate_Aortic_Regurgitation_AR: "N/A",
            Greater_Equal_Moderate_Mitral_Regurgitation_MR: "N/A",
            Left_Ventricular_End_Diastolic_Volume_LVEDV: "N/A",
            Left_Ventricular_End_Systolic_Volume_LVESV: "N/A",
            Aortic_Valve_Annular_Area: "N/A",
            Aortic_Valve_Average_Annular_Diameter: "N/A",
            Aortic_Valve_Minimum_Annular_Diameter: "N/A",
            Aortic_Valve_Maximum_Annular_Diameter: "N/A",
            Aortic_Valve_Annular_Perimeter: "N/A",
            Aortic_Valve_Annular_Eccentricity_Index: "N/A",
            Aortic_Valve_Area_Derived_Annular_Diameter: "N/A",
            Aortic_Valve_Perimeter_Derived_Annular_Diameter: "N/A",
            Aortic_Sinotubular_Junction_STJ_Diameter: "N/A",
            Aortic_Sinus_Diameter_Sinus_Of_Valsalva: "N/A",
            Ascending_Aorta_Diameter_Measured_At_The_Level_Of_The_Pulmonary_Artery_Bifurcation: "N/A",
            Supraannular_Calcification_Aortic_Valve: "N/A",
            Annular_Calcification_Aortic_Valve: "N/A",
            Left_Ventricular_Outflow_Tract_LVOT_Calcification: "N/A",
            Left_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Left_Coronary_Ostium: "N/A",
            Right_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Right_Coronary_Ostium: "N/A"
        },
        Procedural_Details: {
            Transfemoral_approach: "N/A",
            Transapical_approach: "N/A",
            Other_approaches: "N/A",
            THV_size_less_equal_twenty_five_mm: "N/A",
            THV_size_greater_equal_twenty_six_mm: "N/A",
            THV_type_self_expandable_or_balloon_expandable: "N/A",
            Pre_dilation: "N/A",
            Post_dilation: "N/A",
            Total_procedure_time: "N/A",
            Fluoroscopy_time: "N/A",
            Contrast_volume: "N/A",
            Immediate_post_procedural_LVEF: "N/A",
            Immediate_post_procedural_aortic_valve_PG: "N/A",
            Post_procedural_aortic_valve_PG_greater_equal_twenty_mmHg: "N/A",
            Prosthesis_malposition: "N/A",
            Annular_rupture: "N/A",
            Excessive_oversizing: "N/A",
            Oversizing_greater_equal_fifteen_percent: "N/A",
            Immediate_post_procedural_PVL_yes_no: "N/A",
            PVL_severity: "N/A",
            THV_displacement: "N/A",
            Conversion_to_SAVR: "N/A",
            Conversion_to_CPB: "N/A",
            Valve_in_valve: "N/A",
            Periprocedural_death: "N/A"
        },
        Evaluation_Before_Discharge: {
            Death_before_discharge: "N/A",
            Adverse_cardiovascular_events: "N/A",
            Stroke: "N/A",
            Life_threatening_bleeding: "N/A",
            Acute_kidney_injury: "N/A",
            Major_vascular_complication: "N/A",
            New_permanent_pacemaker_implantation: "N/A",
            PVL_before_discharge_yes_no: "N/A",
            PVL_severity_before_discharge: "N/A",
            Maximum_aortic_valve_PG_before_discharge: "N/A",
            Mean_aortic_valve_PG_before_discharge: "N/A",
            EOA_index_before_discharge: "N/A"
        },
        Follow_up_Characteristics: {
            thirty_day_all_cause_mortality: "N/A",
            thirty_day_myocardial_infarction: "N/A",
            thirty_day_stroke: "N/A",
            thirty_day_heart_failure_readmission: "N/A",
            one_year_all_cause_mortality: "N/A",
            one_year_myocardial_infarction: "N/A",
            one_year_stroke: "N/A",
            one_year_heart_failure_readmission: "N/A",
            Left_ventricular_ejection_fraction_LVEF: "N/A",
            Maximum_aortic_valve_PG: "N/A",
            Mean_aortic_valve_PG: "N/A",
            Effective_orifice_area_EOA: "N/A",
            Effective_orifice_area_index_EOAi: "N/A",
            PVL_yes_no: "N/A",
            PVL_severity: "N/A"
        }
    },
    {
        id: 332,
        doi: "10.1001/jamainternmed.2016.9356",
        pmid: "28192558",
        title: "Abnormal Electrocardiogram in a Woman With Atrial Fibrillation and Recent Care Transition",
        source: "JAMA INTERNAL MEDICINE",
        author: "Katie E Raffel, Nora Goldschlager",
        abstract: "N/A",
        keywords: null,
        year: 2017,
        Basic_Info: {
            Age: "80",
            Gender: "Female",
            Case: "Severe symptomatic aortic stenosis, atrial fibrillation, moderate mitral stenosis",
            Previous_History: "Chronic atrial fibrillation, left intraventricular conduction delay"
        },
        Pre_Info: {
            Mean_Gradient: "5 mmHg",
            Peak_Gradients: "12 mmHg",
            Valve_Area: "1.4 cm²",
            Maximum_Velocity: "N/A",
            Ejection_Fraction: "N/A"
        },
        Procedure: {
            Valve_Diameter: "N/A",
            Valve_Type: "N/A"
        },
        Result: {
            Death: false,
            Paravalvular_Leak: false,
            Mean_Gradient: "N/A",
            Peak_Gradients: "N/A",
            Valve_Area: "N/A",
            Maximum_Velocity: "N/A"
        },
        Files: {
            PDF: "D:/Romy/SAIRI/TAVI/Code/pdf_downloads/10.1001_jamainternmed.2016.9356.pdf",
            Images: [
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1001_jamainternmed.2016.9356/images/1cd32a3dcd8a915aafea3bd98303d008dbd99236c833ca76467ba13f66af6aa0.jpg",
                    caption: "Electrocardiographic Results at Admission"
                }
            ]
        },
        Baseline_Characteristics: {
            Age: 80,
            Sex: "N/A",
            Body_Mass_Index_BMI: "N/A",
            Surface_Area: "N/A",
            Diabetes_Mellitus: "N/A",
            Hypertension: "N/A",
            Hyperlipidemia: "N/A",
            Coronary_Artery_Disease: "N/A",
            Chronic_Obstructive_Pulmonary_Disease_COPD: "N/A",
            Dialysis: "N/A",
            Atrial_Fibrillation: true,
            New_York_Heart_Association_NYHA_Classification: "N/A",
            Angiotensin_Converting_Enzyme_Inhibitor_ACEI_or_Angiotensin_II_Receptor_Blocker_ARB: "N/A",
            Beta_Receptor_Blocker: true,
            Calcium_Ion_Blocker: true,
            Diuretic: true,
            Aspirin: "N/A",
            Anticoagulant: true,
            Statins: true,
            Myocardial_Infarction: "N/A",
            Percutaneous_Coronary_Intervention_PCI: "N/A",
            Coronary_Artery_Bypass_Grafting_CABG: "N/A",
            Society_of_Thoracic_Surgeons_STS_Score: "N/A",
            N_Terminal_Pro_B_Type_Natriuretic_Peptide_NT_proBNP: "N/A"
        },
        Preprocedural_Imaging_Assessment: {
            Left_Ventricular_Ejection_Fraction_LVEF: "N/A",
            Aortic_Valve_Maximum_Transvalvular_Pressure_Gradient_Max_PG: "N/A",
            Aortic_Valve_Mean_Transvalvular_Pressure_Gradient_Mean_PG: "N/A",
            Aortic_Valve_Effective_Orifice_Area_EOA: "N/A",
            Aortic_Valve_Effective_Orifice_Area_Index_EOAI: "N/A",
            Greater_Equal_Moderate_Aortic_Regurgitation_AR: "N/A",
            Greater_Equal_Moderate_Mitral_Regurgitation_MR: true,
            Left_Ventricular_End_Diastolic_Volume_LVEDV: "N/A",
            Left_Ventricular_End_Systolic_Volume_LVESV: "N/A",
            Aortic_Valve_Annular_Area: "N/A",
            Aortic_Valve_Average_Annular_Diameter: "N/A",
            Aortic_Valve_Minimum_Annular_Diameter: "N/A",
            Aortic_Valve_Maximum_Annular_Diameter: "N/A",
            Aortic_Valve_Annular_Perimeter: "N/A",
            Aortic_Valve_Annular_Eccentricity_Index: "N/A",
            Aortic_Valve_Area_Derived_Annular_Diameter: "N/A",
            Aortic_Valve_Perimeter_Derived_Annular_Diameter: "N/A",
            Aortic_Sinotubular_Junction_STJ_Diameter: "N/A",
            Aortic_Sinus_Diameter_Sinus_Of_Valsalva: "N/A",
            Ascending_Aorta_Diameter_Measured_At_The_Level_Of_The_Pulmonary_Artery_Bifurcation: "N/A",
            Supraannular_Calcification_Aortic_Valve: "N/A",
            Annular_Calcification_Aortic_Valve: "N/A",
            Left_Ventricular_Outflow_Tract_LVOT_Calcification: "N/A",
            Left_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Left_Coronary_Ostium: "N/A",
            Right_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Right_Coronary_Ostium: "N/A"
        },
        Procedural_Details: {
            Transfemoral_approach: true,
            Transapical_approach: "N/A",
            Other_approaches: "N/A",
            THV_size_less_equal_twenty_five_mm: "N/A",
            THV_size_greater_equal_twenty_six_mm: "N/A",
            THV_type_self_expandable_or_balloon_expandable: "N/A",
            Pre_dilation: "N/A",
            Post_dilation: "N/A",
            Total_procedure_time: "N/A",
            Fluoroscopy_time: "N/A",
            Contrast_volume: "N/A",
            Immediate_post_procedural_LVEF: "N/A",
            Immediate_post_procedural_aortic_valve_PG: "N/A",
            Post_procedural_aortic_valve_PG_greater_equal_twenty_mmHg: "N/A",
            Prosthesis_malposition: "N/A",
            Annular_rupture: "N/A",
            Excessive_oversizing: "N/A",
            Oversizing_greater_equal_fifteen_percent: "N/A",
            Immediate_post_procedural_PVL_yes_no: "N/A",
            PVL_severity: "N/A",
            THV_displacement: "N/A",
            Conversion_to_SAVR: "N/A",
            Conversion_to_CPB: "N/A",
            Valve_in_valve: "N/A",
            Periprocedural_death: "N/A"
        },
        Evaluation_Before_Discharge: {
            Death_before_discharge: false,
            Adverse_cardiovascular_events: "N/A",
            Stroke: "N/A",
            Life_threatening_bleeding: "N/A",
            Acute_kidney_injury: "N/A",
            Major_vascular_complication: "N/A",
            New_permanent_pacemaker_implantation: "N/A",
            PVL_before_discharge_yes_no: "N/A",
            PVL_severity_before_discharge: "N/A",
            Maximum_aortic_valve_PG_before_discharge: "N/A",
            Mean_aortic_valve_PG_before_discharge: "N/A",
            EOA_index_before_discharge: "N/A"
        },
        Follow_up_Characteristics: {
            thirty_day_all_cause_mortality: "N/A",
            thirty_day_myocardial_infarction: "N/A",
            thirty_day_stroke: "N/A",
            thirty_day_heart_failure_readmission: "N/A",
            one_year_all_cause_mortality: "N/A",
            one_year_myocardial_infarction: "N/A",
            one_year_stroke: "N/A",
            one_year_heart_failure_readmission: "N/A",
            Left_ventricular_ejection_fraction_LVEF: "N/A",
            Maximum_aortic_valve_PG: "N/A",
            Mean_aortic_valve_PG: "N/A",
            Effective_orifice_area_EOA: "N/A",
            Effective_orifice_area_index_EOAi: "N/A",
            PVL_yes_no: "N/A",
            PVL_severity: "N/A"
        }
    },
    {
        id: 365,
        doi: "10.1001/jamaneurol.2018.1178",
        pmid: "29813143",
        title: "Cerebral Embolus From Aortic Valve Fragment",
        source: "JAMA NEUROLOGY",
        author: "Saeed A Alqahtani, Itshac Itsik Ben-Dor, Ai-Hsi Liu",
        abstract: "N/A",
        keywords: null,
        year: 2018,
        Basic_Info: {
            Age: "80",
            Gender: "Female",
            Case: "Severe aortic stenosis",
            Previous_History: "Recent retroperitoneal hemorrhage"
        },
        Pre_Info: {
            Mean_Gradient: "N/A",
            Peak_Gradients: "N/A",
            Valve_Area: "N/A",
            Maximum_Velocity: "N/A",
            Ejection_Fraction: "N/A"
        },
        Procedure: {
            Valve_Diameter: "N/A",
            Valve_Type: "N/A"
        },
        Result: {
            Death: false,
            Paravalvular_Leak: false,
            Mean_Gradient: "N/A",
            Peak_Gradients: "N/A",
            Valve_Area: "N/A",
            Maximum_Velocity: "N/A"
        },
        Files: {
            PDF: "D:/Romy/SAIRI/TAVI/Code/pdf_downloads/10.1001_jamaneurol.2018.1178.pdf",
            Images: [
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1001_jamaneurol.2018.1178/images/d0e7d20915aac4aade0771c94cc70d1aad8dc45b2e6dc7b385caf737e6c2f8fd.jpg",
                    caption: "N/A"
                }
            ]
        },
        Baseline_Characteristics: {
            Age: 80,
            Sex: "female",
            Body_Mass_Index_BMI: "N/A",
            Surface_Area: "N/A",
            Diabetes_Mellitus: "N/A",
            Hypertension: "N/A",
            Hyperlipidemia: "N/A",
            Coronary_Artery_Disease: "N/A",
            Chronic_Obstructive_Pulmonary_Disease_COPD: "N/A",
            Dialysis: "N/A",
            Atrial_Fibrillation: "N/A",
            New_York_Heart_Association_NYHA_Classification: "N/A",
            Angiotensin_Converting_Enzyme_Inhibitor_ACEI_or_Angiotensin_II_Receptor_Blocker_ARB: "N/A",
            Beta_Receptor_Blocker: "N/A",
            Calcium_Ion_Blocker: "N/A",
            Diuretic: "N/A",
            Aspirin: "N/A",
            Anticoagulant: "N/A",
            Statins: "N/A",
            Myocardial_Infarction: "N/A",
            Percutaneous_Coronary_Intervention_PCI: "N/A",
            Coronary_Artery_Bypass_Grafting_CABG: "N/A",
            Society_of_Thoracic_Surgeons_STS_Score: "N/A",
            N_Terminal_Pro_B_Type_Natriuretic_Peptide_NT_proBNP: "N/A"
        },
        Preprocedural_Imaging_Assessment: {
            Left_Ventricular_Ejection_Fraction_LVEF: "N/A",
            Aortic_Valve_Maximum_Transvalvular_Pressure_Gradient_Max_PG: "N/A",
            Aortic_Valve_Mean_Transvalvular_Pressure_Gradient_Mean_PG: "N/A",
            Aortic_Valve_Effective_Orifice_Area_EOA: "N/A",
            Aortic_Valve_Effective_Orifice_Area_Index_EOAI: "N/A",
            Greater_Equal_Moderate_Aortic_Regurgitation_AR: "N/A",
            Greater_Equal_Moderate_Mitral_Regurgitation_MR: "N/A",
            Left_Ventricular_End_Diastolic_Volume_LVEDV: "N/A",
            Left_Ventricular_End_Systolic_Volume_LVESV: "N/A",
            Aortic_Valve_Annular_Area: "N/A",
            Aortic_Valve_Average_Annular_Diameter: "N/A",
            Aortic_Valve_Minimum_Annular_Diameter: "N/A",
            Aortic_Valve_Maximum_Annular_Diameter: "N/A",
            Aortic_Valve_Annular_Perimeter: "N/A",
            Aortic_Valve_Annular_Eccentricity_Index: "N/A",
            Aortic_Valve_Area_Derived_Annular_Diameter: "N/A",
            Aortic_Valve_Perimeter_Derived_Annular_Diameter: "N/A",
            Aortic_Sinotubular_Junction_STJ_Diameter: "N/A",
            Aortic_Sinus_Diameter_Sinus_Of_Valsalva: "N/A",
            Ascending_Aorta_Diameter_Measured_At_The_Level_Of_The_Pulmonary_Artery_Bifurcation: "N/A",
            Supraannular_Calcification_Aortic_Valve: "N/A",
            Annular_Calcification_Aortic_Valve: "N/A",
            Left_Ventricular_Outflow_Tract_LVOT_Calcification: "N/A",
            Left_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Left_Coronary_Ostium: "N/A",
            Right_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Right_Coronary_Ostium: "N/A"
        },
        Procedural_Details: {
            Transfemoral_approach: "N/A",
            Transapical_approach: "N/A",
            Other_approaches: "N/A",
            THV_size_less_equal_twenty_five_mm: "N/A",
            THV_size_greater_equal_twenty_six_mm: "N/A",
            THV_type_self_expandable_or_balloon_expandable: "bioprosthetic",
            Pre_dilation: "N/A",
            Post_dilation: "true",
            Total_procedure_time: "N/A",
            Fluoroscopy_time: "N/A",
            Contrast_volume: "N/A",
            Immediate_post_procedural_LVEF: "N/A",
            Immediate_post_procedural_aortic_valve_PG: "N/A",
            Post_procedural_aortic_valve_PG_greater_equal_twenty_mmHg: "N/A",
            Prosthesis_malposition: "N/A",
            Annular_rupture: "N/A",
            Excessive_oversizing: "N/A",
            Oversizing_greater_equal_fifteen_percent: "N/A",
            Immediate_post_procedural_PVL_yes_no: "N/A",
            PVL_severity: "N/A",
            THV_displacement: "N/A",
            Conversion_to_SAVR: "N/A",
            Conversion_to_CPB: "N/A",
            Valve_in_valve: "N/A",
            Periprocedural_death: "N/A"
        },
        Evaluation_Before_Discharge: {
            Death_before_discharge: "N/A",
            Adverse_cardiovascular_events: "N/A",
            Stroke: "N/A",
            Life_threatening_bleeding: "N/A",
            Acute_kidney_injury: "N/A",
            Major_vascular_complication: "N/A",
            New_permanent_pacemaker_implantation: "N/A",
            PVL_before_discharge_yes_no: "N/A",
            PVL_severity_before_discharge: "N/A",
            Maximum_aortic_valve_PG_before_discharge: "N/A",
            Mean_aortic_valve_PG_before_discharge: "N/A",
            EOA_index_before_discharge: "N/A"
        },
        Follow_up_Characteristics: {
            thirty_day_all_cause_mortality: "N/A",
            thirty_day_myocardial_infarction: "N/A",
            thirty_day_stroke: "N/A",
            thirty_day_heart_failure_readmission: "N/A",
            one_year_all_cause_mortality: "N/A",
            one_year_myocardial_infarction: "N/A",
            one_year_stroke: "N/A",
            one_year_heart_failure_readmission: "N/A",
            Left_ventricular_ejection_fraction_LVEF: "N/A",
            Maximum_aortic_valve_PG: "N/A",
            Mean_aortic_valve_PG: "N/A",
            Effective_orifice_area_EOA: "N/A",
            Effective_orifice_area_index_EOAi: "N/A",
            PVL_yes_no: "N/A",
            PVL_severity: "N/A"
        }
    },
    {
        id: 357,
        doi: "10.1002/ajmg.a.40377",
        pmid: "30195254",
        title: "Geleophysic dysplasia: 48 year clinical update with emphasis on cardiac care",
        source: "AMERICAN JOURNAL OF MEDICAL GENETICS PART A",
        author: "Janet M Legare, Peggy Modaff, Samuel P Strom, Richard M Pauli, Heather L Bartlett",
        abstract: "Geleophysic dysplasia is a rare skeletal dysplasia often complicated by progressive cardiac disease. Information about long-term outcomes is limited. A clinical update of the oldest surviving patient described with geleophysic dysplasia type 1 is provided. Special note is made in relation to the cardiac disease and interventions. Genetic testing of ADAMTSL2 revealed a previously reported missense mutation as well as a novel nonsense mutation, which can be added to the list of causative mutations in geleophysic dysplasia.",
        keywords: "ADAMTSL2; GD1; TAVR; aortic aneurysm; aortic stenosis; geleophysic dysplasia.",
        year: 2018,
        Basic_Info: {
            Age: "48",
            Gender: "Male",
            Case: "Geleophysic dysplasia type 1 with progressive cardiac disease",
            Previous_History: "Aortic, mitral, and pulmonary valve disease; arthritis; restrictive lung disease; moderate to severe mixed hearing loss"
        },
        Pre_Info: {
            Mean_Gradient: "57 mmHg",
            Peak_Gradients: "N/A",
            Valve_Area: "N/A",
            Maximum_Velocity: "N/A",
            Ejection_Fraction: "35%"
        },
        Procedure: {
            Valve_Diameter: "23 mm",
            Valve_Type: "CoreValve"
        },
        Result: {
            Death: false,
            Paravalvular_Leak: false,
            Mean_Gradient: "17 mmHg",
            Peak_Gradients: "N/A",
            Valve_Area: "N/A",
            Maximum_Velocity: "N/A"
        },
        Files: {
            PDF: "D:/Romy/SAIRI/TAVI/Code/pdf_downloads/10.1002_ajmg.a.40377.pdf",
            Images: [
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1002_ajmg.a.40377/images/25aad5dd44211952122192309bcad2019fd9f500bb54f0bef75d7f438e2d6d92.jpg",
                    caption: "Clinical features. (a-e) Typical facies seen in geleophysic dysplasia type 1 (GD1) including smooth philtrum, thin upper vermilian, long and upturned mouth, no enamel defects, and micrognathia. Features were stable with age, no coarsening. Note the hearing aid in (d). (f,g,h) Extremity findings including brachydactyly, progressive DIP and PIP contractures, and plantar flexion contractures. No evidence of clubbing was found. (i-I) Typical posture and proportions with micromelia, relative acromelia, joint contractures, and thickened skin over knees and ankles. Chest is short and broad. The patient was 3 years in (a,i), 9 years in (h,j), 13 years in (b,f ), 22 years in (c), and 48 years in (d,e,k) [Color figure can be viewed at wileyonlinelibrary.com]"
                },
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1002_ajmg.a.40377/images/b71d24e024387ab789e0777652e399a723d2041b0863f4e344e2df4977ee1a0b.jpg",
                    caption: "Multiplanar reformations of computed tomographic images show (a) left ventricular outflow tract with a thickened calcified aortic valve (white arrow) with an annulus dimension of 18  12 mm and a subaortic membrane (yellow arrow); (b) dilated ascending aorta. (Ao) measured 3.2 cm (2.4 cm/m?, Z score + 4.3), dilated brachiocephalic artery (BC), and dilated main pulmonary artery (PA) with a maximum dimension of 4.3 cm (Z score + 6.7); (c) iliofemoral arteries with minimum intraluminal dimension of 6.4 mm; (d) pectus excavatum with the sternum abutting the right ventricular free wall; (e) thoracic scoliosis and dilated descending aorta; and (f ) tracheobronchial tree demonstrating bronchomalacia. The patient was successfully treated by transcatheter aortic valve implantation using a 23 mm CoreValve Evolut-R (Medtronic) via a right transfemoral approach [Color figure can be viewed at wileyonlinelibrary.com]"
                }
            ]
        },
        Baseline_Characteristics: {
            Age: 48,
            Sex: "N/A",
            Body_Mass_Index_BMI: "N/A",
            Surface_Area: "N/A",
            Diabetes_Mellitus: "N/A",
            Hypertension: "N/A",
            Hyperlipidemia: "N/A",
            Coronary_Artery_Disease: "N/A",
            Chronic_Obstructive_Pulmonary_Disease_COPD: "N/A",
            Dialysis: "N/A",
            Atrial_Fibrillation: "N/A",
            New_York_Heart_Association_NYHA_Classification: "III",
            Angiotensin_Converting_Enzyme_Inhibitor_ACEI_or_Angiotensin_II_Receptor_Blocker_ARB: "N/A",
            Beta_Receptor_Blocker: "N/A",
            Calcium_Ion_Blocker: "N/A",
            Diuretic: "N/A",
            Aspirin: "N/A",
            Anticoagulant: "N/A",
            Statins: "N/A",
            Myocardial_Infarction: "N/A",
            Percutaneous_Coronary_Intervention_PCI: "N/A",
            Coronary_Artery_Bypass_Grafting_CABG: "N/A",
            Society_of_Thoracic_Surgeons_STS_Score: "N/A",
            N_Terminal_Pro_B_Type_Natriuretic_Peptide_NT_proBNP: "N/A"
        },
        Preprocedural_Imaging_Assessment: {
            Left_Ventricular_Ejection_Fraction_LVEF: 35,
            Aortic_Valve_Maximum_Transvalvular_Pressure_Gradient_Max_PG: 57,
            Aortic_Valve_Mean_Transvalvular_Pressure_Gradient_Mean_PG: "N/A",
            Aortic_Valve_Effective_Orifice_Area_EOA: "N/A",
            Aortic_Valve_Effective_Orifice_Area_Index_EOAI: "N/A",
            Greater_Equal_Moderate_Aortic_Regurgitation_AR: true,
            Greater_Equal_Moderate_Mitral_Regurgitation_MR: true,
            Left_Ventricular_End_Diastolic_Volume_LVEDV: "N/A",
            Left_Ventricular_End_Systolic_Volume_LVESV: "N/A",
            Aortic_Valve_Annular_Area: "N/A",
            Aortic_Valve_Average_Annular_Diameter: "N/A",
            Aortic_Valve_Minimum_Annular_Diameter: "N/A",
            Aortic_Valve_Maximum_Annular_Diameter: "N/A",
            Aortic_Valve_Annular_Perimeter: "N/A",
            Aortic_Valve_Annular_Eccentricity_Index: "N/A",
            Aortic_Valve_Area_Derived_Annular_Diameter: "N/A",
            Aortic_Valve_Perimeter_Derived_Annular_Diameter: "N/A",
            Aortic_Sinotubular_Junction_STJ_Diameter: "N/A",
            Aortic_Sinus_Diameter_Sinus_Of_Valsalva: "N/A",
            Ascending_Aorta_Diameter_Measured_At_The_Level_Of_The_Pulmonary_Artery_Bifurcation: 3.2,
            Supraannular_Calcification_Aortic_Valve: "N/A",
            Annular_Calcification_Aortic_Valve: "N/A",
            Left_Ventricular_Outflow_Tract_LVOT_Calcification: "N/A",
            Left_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Left_Coronary_Ostium: "N/A",
            Right_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Right_Coronary_Ostium: "N/A"
        },
        Procedural_Details: {
            Transfemoral_approach: true,
            Transapical_approach: "N/A",
            Other_approaches: "N/A",
            THV_size_less_equal_twenty_five_mm: 23,
            THV_size_greater_equal_twenty_six_mm: false,
            THV_type_self_expandable_or_balloon_expandable: "self-expandable",
            Pre_dilation: "N/A",
            Post_dilation: "N/A",
            Total_procedure_time: "N/A",
            Fluoroscopy_time: "N/A",
            Contrast_volume: "N/A",
            Immediate_post_procedural_LVEF: 75,
            Immediate_post_procedural_aortic_valve_PG: 17,
            Post_procedural_aortic_valve_PG_greater_equal_twenty_mmHg: false,
            Prosthesis_malposition: "N/A",
            Annular_rupture: "N/A",
            Excessive_oversizing: "N/A",
            Oversizing_greater_equal_fifteen_percent: "N/A",
            Immediate_post_procedural_PVL_yes_no: "N/A",
            PVL_severity: "N/A",
            THV_displacement: "N/A",
            Conversion_to_SAVR: "N/A",
            Conversion_to_CPB: "N/A",
            Valve_in_valve: "N/A",
            Periprocedural_death: "N/A"
        },
        Evaluation_Before_Discharge: {
            Death_before_discharge: false,
            Adverse_cardiovascular_events: "N/A",
            Stroke: "N/A",
            Life_threatening_bleeding: "N/A",
            Acute_kidney_injury: "N/A",
            Major_vascular_complication: "N/A",
            New_permanent_pacemaker_implantation: "N/A",
            PVL_before_discharge_yes_no: "N/A",
            PVL_severity_before_discharge: "N/A",
            Maximum_aortic_valve_PG_before_discharge: 17,
            Mean_aortic_valve_PG_before_discharge: "N/A",
            EOA_index_before_discharge: "N/A"
        },
        Follow_up_Characteristics: {
            thirty_day_all_cause_mortality: "N/A",
            thirty_day_myocardial_infarction: "N/A",
            thirty_day_stroke: "N/A",
            thirty_day_heart_failure_readmission: "N/A",
            one_year_all_cause_mortality: "N/A",
            one_year_myocardial_infarction: "N/A",
            one_year_stroke: "N/A",
            one_year_heart_failure_readmission: "N/A",
            Left_ventricular_ejection_fraction_LVEF: 75,
            Maximum_aortic_valve_PG: 17,
            Mean_aortic_valve_PG: "N/A",
            Effective_orifice_area_EOA: "N/A",
            Effective_orifice_area_index_EOAi: "N/A",
            PVL_yes_no: "N/A",
            PVL_severity: "N/A"
        }
    },
    {
        id: 1,
        doi: "10.1002/ccd.22168",
        pmid: "19626691",
        title: "Valve-in-Valve for the Treatment of Paravalvular Leaks Following Transcatheter Aortic Valve Implantation",
        source: "CATHETERIZATION AND CARDIOVASCULAR INTERVENTIONS",
        author: "Josep Rodés-Cabau, Eric Dumont, Daniel Doyle",
        abstract: "Transcatheter aortic valve implantation (TAVI) is commonly associated with some degree of aortic regurgitation (AR) secondary to the presence of paravalvular leaks. We present the case of an 86-year-old woman diagnosed with severe aortic stenosis who underwent TAVI with a 23-mm Edwards-SAPIEN valve. The procedure complicated with a severe paravalvular leak following TAVI that was unresponsive to balloon postdilation. This complication was successfully managed with the implantation of a second valve of the same diameter within the first one (/\"valve-in-valve/\") resulting in trivial residual AR and the absence of significant transvalvular gradient at the end of the procedure.",
        keywords: null,
        year: 2009,
        Basic_Info: {
            Age: "86",
            Gender: "Female",
            Case: "Severe aortic stenosis",
            Previous_History: "Coronary artery disease, previous bypass grafting, coronary angioplasty, chronic renal failure (creatinine clearance: 34 ml/min)"
        },
        Pre_Info: {
            Mean_Gradient: "31 mmHg",
            Peak_Gradients: "N/A",
            Valve_Area: "0.70 cm²",
            Maximum_Velocity: "N/A",
            Ejection_Fraction: "60%"
        },
        Procedure: {
            Valve_Diameter: "23 mm",
            Valve_Type: "Edwards SAPIEN"
        },
        Result: {
            Death: false,
            Paravalvular_Leak: false,
            Mean_Gradient: "8 mmHg",
            Peak_Gradients: "N/A",
            Valve_Area: "1.22 cm²",
            Maximum_Velocity: "N/A"
        },
        Files: {
            PDF: "D:/Romy/SAIRI/TAVI/Code/pdf_downloads/10.1002_ccd.22168.pdf",
            Images: [
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1002_ccd.22168/images/597acb3fe8559c504babb648610d406c78099a0e0d496c0b96746737be356d6f.jpg",
                    caption: "Transesophageal echocardiograhy images [(A), long axis view; (B), short axis view]. following transcatheter valve implantation showing the presence of severe paravalvular aortic regurgitation (white arrows). [Color figure can be viewed in the online issue, which is available at www.interscience.wiley.com.]"
                },
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1002_ccd.22168/images/3a43e4cfbcc4d1e9841bd9d8130510ae2680c2fd4c1a95a6722bb4c0ce684c0b.jpg",
                    caption: "Fluoroscopy and angiographic images showing (A) the positioning of a second Edwards-SAPIEN valve (thick white arrow) within the first one (thin white arrow), (B) implanta-. tion of the second valve, and (C) following implantation of the second valve.."
                },
                {
                    path: "D:/Romy/SAIRI/TAVI/Code/extract_downloads/10.1002_ccd.22168/images/c6a38931371a39c62763a11a0b3d2cb345e5e6698d8a1f3dc098bdb8d50ee3c6.jpg",
                    caption: "Transesophageal echocardiography images [(A), long axis view; (B), short axis view]. following valve-in-valve implantation showing trivial paravalvular leak (white arrows). [Color figure can be viewed in the online issue, which is available at www.interscience.wiley.com.]"
                }
            ]
        },
        Baseline_Characteristics: {
            Age: 86,
            Sex: "female",
            Body_Mass_Index_BMI: "N/A",
            Surface_Area: "N/A",
            Diabetes_Mellitus: "N/A",
            Hypertension: "N/A",
            Hyperlipidemia: "N/A",
            Coronary_Artery_Disease: true,
            Chronic_Obstructive_Pulmonary_Disease_COPD: "N/A",
            Dialysis: "N/A",
            Atrial_Fibrillation: true,
            New_York_Heart_Association_NYHA_Classification: "II",
            Angiotensin_Converting_Enzyme_Inhibitor_ACEI_or_Angiotensin_II_Receptor_Blocker_ARB: "N/A",
            Beta_Receptor_Blocker: "N/A",
            Calcium_Ion_Blocker: "N/A",
            Diuretic: "N/A",
            Aspirin: "N/A",
            Anticoagulant: "N/A",
            Statins: "N/A",
            Myocardial_Infarction: "N/A",
            Percutaneous_Coronary_Intervention_PCI: true,
            Coronary_Artery_Bypass_Grafting_CABG: true,
            Society_of_Thoracic_Surgeons_STS_Score: 7.8,
            N_Terminal_Pro_B_Type_Natriuretic_Peptide_NT_proBNP: "N/A"
        },
        Preprocedural_Imaging_Assessment: {
            Left_Ventricular_Ejection_Fraction_LVEF: 60,
            Aortic_Valve_Maximum_Transvalvular_Pressure_Gradient_Max_PG: 31,
            Aortic_Valve_Mean_Transvalvular_Pressure_Gradient_Mean_PG: "N/A",
            Aortic_Valve_Effective_Orifice_Area_EOA: 0.7,
            Aortic_Valve_Effective_Orifice_Area_Index_EOAI: "N/A",
            Greater_Equal_Moderate_Aortic_Regurgitation_AR: true,
            Greater_Equal_Moderate_Mitral_Regurgitation_MR: "N/A",
            Left_Ventricular_End_Diastolic_Volume_LVEDV: "N/A",
            Left_Ventricular_End_Systolic_Volume_LVESV: "N/A",
            Aortic_Valve_Annular_Area: "N/A",
            Aortic_Valve_Average_Annular_Diameter: 20.5,
            Aortic_Valve_Minimum_Annular_Diameter: "N/A",
            Aortic_Valve_Maximum_Annular_Diameter: "N/A",
            Aortic_Valve_Annular_Perimeter: "N/A",
            Aortic_Valve_Annular_Eccentricity_Index: "N/A",
            Aortic_Valve_Area_Derived_Annular_Diameter: "N/A",
            Aortic_Valve_Perimeter_Derived_Annular_Diameter: "N/A",
            Aortic_Sinotubular_Junction_STJ_Diameter: "N/A",
            Aortic_Sinus_Diameter_Sinus_Of_Valsalva: "N/A",
            Ascending_Aorta_Diameter_Measured_At_The_Level_Of_The_Pulmonary_Artery_Bifurcation: "N/A",
            Supraannular_Calcification_Aortic_Valve: "N/A",
            Annular_Calcification_Aortic_Valve: "N/A",
            Left_Ventricular_Outflow_Tract_LVOT_Calcification: "N/A",
            Left_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Left_Coronary_Ostium: "N/A",
            Right_Coronary_Artery_Ostium_Height_From_Aortic_Annulus_To_Right_Coronary_Ostium: "N/A"
        },
        Procedural_Details: {
            Transfemoral_approach: false,
            Transapical_approach: true,
            Other_approaches: "N/A",
            THV_size_less_equal_twenty_five_mm: 23,
            THV_size_greater_equal_twenty_six_mm: false,
            THV_type_self_expandable_or_balloon_expandable: "N/A",
            Pre_dilation: false,
            Post_dilation: true,
            Total_procedure_time: "N/A",
            Fluoroscopy_time: "N/A",
            Contrast_volume: "N/A",
            Immediate_post_procedural_LVEF: "N/A",
            Immediate_post_procedural_aortic_valve_PG: "N/A",
            Post_procedural_aortic_valve_PG_greater_equal_twenty_mmHg: false,
            Prosthesis_malposition: "N/A",
            Annular_rupture: "N/A",
            Excessive_oversizing: "N/A",
            Oversizing_greater_equal_fifteen_percent: "N/A",
            Immediate_post_procedural_PVL_yes_no: true,
            PVL_severity: "N/A",
            THV_displacement: "N/A",
            Conversion_to_SAVR: false,
            Conversion_to_CPB: false,
            Valve_in_valve: true,
            Periprocedural_death: false
        },
        Evaluation_Before_Discharge: {
            Death_before_discharge: false,
            Adverse_cardiovascular_events: "acute renal injury",
            Stroke: "N/A",
            Life_threatening_bleeding: "N/A",
            Acute_kidney_injury: true,
            Major_vascular_complication: "N/A",
            New_permanent_pacemaker_implantation: "N/A",
            PVL_before_discharge_yes_no: true,
            PVL_severity_before_discharge: "trivial",
            Maximum_aortic_valve_PG_before_discharge: 8,
            Mean_aortic_valve_PG_before_discharge: "N/A",
            EOA_index_before_discharge: 1.22
        },
        Follow_up_Characteristics: {
            thirty_day_all_cause_mortality: false,
            thirty_day_myocardial_infarction: "N/A",
            thirty_day_stroke: "N/A",
            thirty_day_heart_failure_readmission: "N/A",
            one_year_all_cause_mortality: "N/A",
            one_year_myocardial_infarction: "N/A",
            one_year_stroke: "N/A",
            one_year_heart_failure_readmission: "N/A",
            Left_ventricular_ejection_fraction_LVEF: "N/A",
            Maximum_aortic_valve_PG: "N/A",
            Mean_aortic_valve_PG: "N/A",
            Effective_orifice_area_EOA: "N/A",
            Effective_orifice_area_index_EOAi: "N/A",
            PVL_yes_no: true,
            PVL_severity: "trivial"
        }
    }
];

module.exports = mergedFilteredTaviCases;